#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Configuration Tasks
  hosts: all
  tasks:

  - name: Change hostname to hampi
    become: yes
    command: hostname hampi

  - name: Enable resizing of (micro)SD card
    become: yes
    command: sed -i 's/ quiet splash plymouth.ignore-serial-consoles$/ quiet init=\/usr\/lib\/raspi-config\/init_resize.sh splash plymouth.ignore-serial-consoles/' /boot/cmdline.txt
    args:
      warn: no

  # This allows apt-add-repository command to be added
  - name: Install software-properties-common Packages
    become: yes
    package:
      name: software-properties-common
      state: present

  - name: Install powermgmt-base Package for unattended-upgrades
    become: yes
    package:
      name: powermgmt-base
      state: present

  - name: Enable mail notifications for unattended-upgrades
    become: yes
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '^\/\/Unattended-Upgrade::Mail \"\";'
      line: Unattended-Upgrade::Mail "pi";

  - name: Add the user 'pi' to group of 'dialout'
    user:
      name: pi
      groups: dialout
      append: yes

  - name: Add the user 'pi' to group of 'plugdev'
    user:
      name: pi
      groups: plugdev
      append: yes

  # Only apply these next two steps to RPi3 and RPi4
  # Note: backup: yes cannot be used on /boot filesystem as
  # it creates an invalid filename pattern which causes this
  # to fail
  - name: Configure Pi to use 64-bit kernel
    become: yes
    blockinfile:
      dest: /boot/config.txt
      block: |
        arm_64bit=1
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Update Pi to use 64-bit Kernel
    become: yes
    command: echo "y" | rpi-update
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Enable Pi VNC Server (32 bit ARM)
    become: yes
    file:
      dest: /etc/systemd/system/multi-user.target.wants/vncserver-x11-serviced.service
      src: /usr/lib/systemd/system/vncserver-x11-serviced.service
      state: link
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"
    ignore_errors: yes

  - name: Start Pi VNC Server (32 bit ARM)
    become: yes
    command: systemctl start vncserver-x11-serviced
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"
    ignore_errors: yes

  - name: Install Pi VNC Server (64 bit ARM)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - tightvncserver
    when: ansible_architecture == "aarch64"

  - name: Create /etc/xdg/pcmanfm/LXDE-pi directory
    become: yes
    file:
      path: /etc/xdg/pcmanfm/LXDE-pi
      state: directory

  - name: Create HamPi desktop config 0 in /etc/xdg/pcmanfm/LXDE-pi
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/etc/xdg/pcmanfm/LXDE-pi/desktop-items-0.conf"
      dest: "/etc/xdg/pcmanfm/LXDE-pi/desktop-items-0.conf"

  - name: Create HamPi desktop config 1 in /etc/xdg/pcmanfm/LXDE-pi
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/etc/xdg/pcmanfm/LXDE-pi/desktop-items-1.conf"
      dest: "/etc/xdg/pcmanfm/LXDE-pi/desktop-items-1.conf"

  - name: Create /home/pi/.config/pcmanfm/LXDE-pi directory
    file:
      path: /home/pi/.config/pcmanfm/LXDE-pi
      state: directory

  - name: Create HamPi desktop config in /home/pi/.config/pcmanfm/LXDE-pi
    copy:
      src: "{{ playbook_dir }}/../files/home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf"
      dest: "/home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf"

  - name: Create /etc/lightdm
    become: yes
    file:
      path: /etc/lightdm
      state: directory

  - name: Create HamPi greeter config in /etc/
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/etc/lightdm/pi-greeter.conf"
      dest: "/etc/lightdm/pi-greeter.conf"

  - name: Create /home/pi/Desktop directory
    file:
      path: /home/pi/Desktop
      state: directory

  - name: Create HamPi README in /home/pi/Desktop
    copy:
      src: "{{ playbook_dir }}/../files/home/pi/Desktop/HAMPI README.doc"
      dest: "/home/pi/Desktop/HAMPI README.doc"

  - name: Create HamPi LICENSE in /home/pi/Desktop
    copy:
      src: "{{ playbook_dir }}/../files/home/pi/Desktop/HAMPI LICENSE.TXT"
      dest: "/home/pi/Desktop/HAMPI LICENSE.TXT"

  - name: Install HamRadio menus
    become: yes
    package:
      name: hamradiomenus
      state: present

  - name: Create /usr/local/share/icons/gnome/16x16/categories directory
    become: yes
    file:
      path: /usr/local/share/icons/gnome/16x16/categories
      state: directory

  - name: Create /usr/local/share/icons/gnome/32x32/categories directory
    become: yes
    file:
      path: /usr/local/share/icons/gnome/32x32/categories
      state: directory

  - name: Create /usr/local/share/icons/gnome/256x256/categories directory
    become: yes
    file:
      path: /usr/local/share/icons/gnome/256x256/categories
      state: directory

  - name: Create icons directory for 512x512
    become: yes
    file:
      path: /usr/local/share/icons/gnome/512x512/categories
      state: directory

  - name: Create /usr/share/icons/gnome/512x512 directory
    become: yes
    file:
      path: /usr/share/icons/gnome/512x512
      state: directory

  - name: Create HamRadio icon 16x16 in /usr/local/share/icons
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/16x16/categories/ham-radio-icon-25.png"
      dest: "/usr/local/share/icons/gnome/16x16/categories/ham-radio-icon-25.png"

  - name: Create HamRadio icon 32x32 in /usr/local/share/icons
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/32x32/categories/ham-radio-icon-25.png"
      dest: "/usr/local/share/icons/gnome/32x32/categories/ham-radio-icon-25.png"

  - name: Create HamRadio icon 256x256 in /usr/local/share/icons
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/256x256/categories/ham-radio-icon-25.png"
      dest: "/usr/local/share/icons/gnome/256x256/categories/ham-radio-icon-25.png"

  - name: Create HamRadio icon 512x512 in /usr/local/share/icons
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/512x512/categories/ham-radio-icon-25.png"
      dest: "/usr/local/share/icons/gnome/512x512/categories/ham-radio-icon-25.png"

  - name: Create HamRadio icon 512x512 in /usr/share/icons/gnome/512x512/
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/512x512/categories/ham-radio-icon-25.png"
      dest: "/usr/share/icons/gnome/512x512/ham-radio-icon-25.png"

  - name: Create /usr/share/icons/hicolor/128x128 directory
    become: yes
    file:
      path: /usr/share/icons/hicolor/128x128
      state: directory

  - name: Create HamRadio icon 512x512 in /usr/share/icons/hicolor/128x128
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/512x512/categories/ham-radio-icon-25.png"
      dest: "/usr/share/icons/hicolor/128x128/ham-radio-icon-25.png"

  - name: Create HamRadio icon 512x512 in /usr/share/icons
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/icons/512x512/categories/ham-radio-icon-25.png"
      dest: "/usr/share/icons/ham-radio-icon-25.png"

  - name: Insert .bash_local configuration
    blockinfile:
      dest: /home/pi/.bash_local
      create: yes
      block: |
        # BUILD OPTIONS
        export MAKEFLAGS="-j `grep processor /proc/cpuinfo | wc -l`"
        export CXXFLAGS='-O2 -march=native -mtune=native'
        export CFLAGS='-O2 -march=native -mtune=native'
        LIBRARY_PATH='/usr/local/lib'
        INCLUDE_PATH='/usr/local/include'
        # For using XTRX and SoapySDR with SDRAngel:
        export LD_LIBRARY_PATH=/usr/local/lib:/opt/install/xtrx-images/lib:$LD_LIBARY_PATH

        # TO PERMIT LAUNCHING X-WINDOWS APPS FROM TERMINAL
        export DISPLAY=:0

        # FIX WSJT-X POPUP BAND/FREQUENCY MENU DISPLAY
        export QT_QPA_PLATFORMTHEME=cleanlooks

        # QRZ.COM AUTHENTICATION FOR WSJTX_TO_N3FJP LOG ADAPTER
        export QRZ_USERNAME=FILLIN
        export QRZ_PASSWORD=FILLIN

  - name: Insert .bashrc configuration
    blockinfile:
      dest: /home/pi/.bashrc
      block: |
        if [ -f ~/.bash_local ]; then
            . ~/.bash_local
        fi
