#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Miscellaneous Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Install Telnet Package
    become: yes
    package:
      name: telnet
      state: present

  - name: Install colrconv Package (convers client with sound and ncurses color support)
    become: yes
    package:
      name: colrconv
      state: present
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Install gcb Package (Utility to calculate long and short path to a location)
    become: yes
    package:
      name: gcb
      state: present
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Install fbb Package (Packet radio mailbox and utilities)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - fbb
      - ax25mail-utils

  - name: Install glfer Package (Program for reception and transmission of QRSS/DFCW signals)
    become: yes
    package:
      name: glfer
      state: present

  # Grig 0.8.1 in repo is latest available as of 2020-02-12
  - name: Install grig Package (Graphical Rig Control based on Hamlib)
    become: yes
    package:
      name: grig
      state: present

  - name: Install gnuais Package (AIS receiver which uses the discriminator output of VHF receivers)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gnuais
      - gnuaisgui

  - name: Install gnss-sdr Package (GLONASS satellite system Software Defined Receiver)
    become: yes
    package:
      name: gnss-sdr
      state: present

  - name: Install linpac Package (terminal for packet radio with mail client)
    become: yes
    package:
      name: linpac
      state: present

  - name: Install acfax Package (Receive faxes using your radio and sound card)
    become: yes
    package:
      name: acfax
      state: present

  - name: Install hamfax Package (Qt based shortwave fax)
    become: yes
    package:
      name: hamfax
      state: present

  - name: Install inspectrum Package (Tool for visualising captured radio signals)
    become: yes
    package:
      name: inspectrum
      state: present

  - name: Install wwl Package (Calculates distance and azimuth between two Maidenhead locators)
    become: yes
    package:
      name: wwl
      state: present

  - name: Install wwl Package (Calculates distance and azimuth between two Maidenhead locators)
    become: yes
    package:
      name: wwl
      state: present

  - name: Install xdx Package (DX-cluster TCP/IP client for amateur radio)
    become: yes
    package:
      name: xdx
      state: present
