#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install CuteSDR
  hosts: all
  tasks:

  - name: Install CuteSdr from repository
    become: yes
    package:
      name: cutesdr
      state: present
