#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Wallpaper Tasks
  hosts: all
  tasks:

  - name: Create /usr/share/rpd-wallpaper directory
    become: yes
    file:
      path: /usr/share/rpd-wallpaper
      state: directory

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/HamPi Desktop Wallpaper.png"
      dest: "/usr/share/rpd-wallpaper/HamPi Desktop Wallpaper.png"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/2300H_1600x1200_AM.jpg"
      dest: "/usr/share/rpd-wallpaper/2300H_1600x1200_AM.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/7300_Wallpaper_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/7300_Wallpaper_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/7610_Wallpaper_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/7610_Wallpaper_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/7800_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/7800_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/AMSATALTLOGO.png"
      dest: "/usr/share/rpd-wallpaper/AMSATALTLOGO.png"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/ARES.png"
      dest: "/usr/share/rpd-wallpaper/ARES.png"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/ARISS pic 1.jpg"
      dest: "/usr/share/rpd-wallpaper/ARISS pic 1.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/ARRL We Do That.jpg"
      dest: "/usr/share/rpd-wallpaper/ARRL We Do That.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Amateur Radio World Map and DXCC Country List.jpg"
      dest: "/usr/share/rpd-wallpaper/Amateur Radio World Map and DXCC Country List.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Antennas Major Design Types.jpg"
      dest: "/usr/share/rpd-wallpaper/Antennas Major Design Types.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Band_Chart_Image_for_ARRL_Web.jpg"
      dest: "/usr/share/rpd-wallpaper/Band_Chart_Image_for_ARRL_Web.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Callsign Prefix List International.jpg"
      dest: "/usr/share/rpd-wallpaper/Callsign Prefix List International.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/DSTAR2_1600x1200_AM.jpg"
      dest: "/usr/share/rpd-wallpaper/DSTAR2_1600x1200_AM.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/DSTAR_Wallpaper_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/DSTAR_Wallpaper_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Elecraft K3s Transceiver.jpg"
      dest: "/usr/share/rpd-wallpaper/Elecraft K3s Transceiver.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/FTDX 9000.jpg"
      dest: "/usr/share/rpd-wallpaper/FTDX 9000.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/ICOM IC-9100.jpg"
      dest: "/usr/share/rpd-wallpaper/ICOM IC-9100.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/ID31APlus_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/ID31APlus_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/InTheCommunity_Wallpaper_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/InTheCommunity_Wallpaper_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Kenwood TS-2000.jpg"
      dest: "/usr/share/rpd-wallpaper/Kenwood TS-2000.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Kenwood TS-590.jpg"
      dest: "/usr/share/rpd-wallpaper/Kenwood TS-590.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Moonbounce.jpg"
      dest: "/usr/share/rpd-wallpaper/Moonbounce.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/R30_Wallpaper_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/R30_Wallpaper_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Space Antenna.jpg"
      dest: "/usr/share/rpd-wallpaper/Space Antenna.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Van mobile radio.jpg"
      dest: "/usr/share/rpd-wallpaper/Van mobile radio.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Very Large Array.jpg"
      dest: "/usr/share/rpd-wallpaper/Very Large Array.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/W100AW.jpg"
      dest: "/usr/share/rpd-wallpaper/W100AW.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/W1AW_Fall.jpg"
      dest: "/usr/share/rpd-wallpaper/W1AW_Fall.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/When all else fails - amateur radio.jpg"
      dest: "/usr/share/rpd-wallpaper/When all else fails - amateur radio.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/World CQ Zones.gif"
      dest: "/usr/share/rpd-wallpaper/World CQ Zones.gif"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/Worlds Largest Radio Telescope.jpg"
      dest: "/usr/share/rpd-wallpaper/Worlds Largest Radio Telescope.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/baofeng.jpg"
      dest: "/usr/share/rpd-wallpaper/baofeng.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/cubesat2.jpg"
      dest: "/usr/share/rpd-wallpaper/cubesat2.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/dstar_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/dstar_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/hf_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/hf_1600x1200.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/j-38 key.jpg"
      dest: "/usr/share/rpd-wallpaper/j-38 key.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/morse-code.jpg"
      dest: "/usr/share/rpd-wallpaper/morse-code.jpg"

  - name: Create HamPi desktop wallpaper in /usr/share/rpd-wallpaper
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/usr/share/rpd-wallpaper/r8600_Wallpaper_1600x1200.jpg"
      dest: "/usr/share/rpd-wallpaper/r8600_Wallpaper_1600x1200.jpg"
