#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install JTDX
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Creates directory hamradio
    file:
      path: /home/pi/hamradio
      state: directory

#  - name: Install dependent components
#    become: yes
#    package:
#      name: "{{ item }}"
#      state: present
#    with_items:
#      - python3
#      - python3-pip

#
# Raspbian (ARM)
#

  - name: Determine latest version of JTDX on web (ARM)
    shell: curl --silent --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "https://www.jtdx.tech/en/" | grep -Po "https://www.jtdx.tech/downloads/Linux/jtdx-.*_armhf.deb" | grep -Po "jtdx-.*_armhf.deb"
    args:
      warn: no
    register: jtdx_name
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - local_action: command echo item
    with_items: jtdx_name.stdout_lines[0]
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Download JTDX {{ jtdx_name.stdout_lines[0] }} (ARM)
    get_url:
      url: "https://www.jtdx.tech/downloads/Linux/{{ jtdx_name.stdout_lines[0] }}"
      dest: /home/pi/hamradio/{{ jtdx_name.stdout_lines[0] }}
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Install JTDX {{ jtdx_name.stdout_lines[0] }} (ARM)
    become: yes
    apt:
      deb: /home/pi/hamradio/{{ jtdx_name.stdout_lines[0] }}
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

#
# Raspbian (x86)
#

  - name: Determine latest version of JTDX on web (x86)
    shell: curl --silent --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "https://www.jtdx.tech/en/" | grep -Po "https://www.jtdx.tech/downloads/Linux/jtdx-.*_i386.deb"  | grep -Po "jtdx-.*_i386.deb"
    args:
      warn: no
    register: jtdx_name
    when: ansible_architecture == "i386"

  - local_action: command echo item
    with_items: jtdx_name.stdout_lines[0]
    when: ansible_architecture == "i386"

  - name: Download JTDX {{ jtdx_name.stdout_lines[0] }} (x86)
    get_url:
      url: "https://www.jtdx.tech/downloads/Linux/{{ jtdx_name.stdout_lines[0] }}"
      dest: /home/pi/hamradio/{{ jtdx_name.stdout_lines[0] }}
    when: ansible_architecture == "i386"

  - name: Install JTDX {{ jtdx_name.stdout_lines[0] }} (x86)
    become: yes
    apt:
      deb: /home/pi/hamradio/{{ jtdx_name.stdout_lines[0] }}
    when: ansible_architecture == "i386"
