#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Digital Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Install linpsk Package (Operate PSK31/RTTY modes with X GUI)
    become: yes
    package:
      name: linpsk
      state: present

  - name: Install multimon Package (Linux Radio Transmission Decoder)
    become: yes
    package:
      name: multimon
      state: present

  - name: Install psk31lx Package (PSK31 terminal application with text-based user interface)
    become: yes
    package:
      name: psk31lx
      state: present

  - name: Install twpsk Package (Soundcard-based X program for operating PSK31)
    become: yes
    package:
      name: twpsk
      state: present
