#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyAirSpy
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Creates directory hamradio
    file:
      path: /home/pi/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gr-osmosdr
      - libfftw3-dev
      - libusb-1.0-0-dev

  - name: Download latest SoapyAirSpy sources
    git:
      repo: https://github.com/pothosware/SoapyAirSpy.git
      dest: /home/pi/hamradio/SoapyAirSpy

  - name: Creates directory SoapyAirSpy/build
    file:
      path: /home/pi/hamradio/SoapyAirSpy/build
      state: directory

  - name: Build SoapyAirSpy CMakeFiles
    command: cmake ..
    args:
      chdir: /home/pi/hamradio/SoapyAirSpy/build

  - name: Build SoapyAirSpy
    command: make
    args:
      chdir: /home/pi/hamradio/SoapyAirSpy/build

  - name: Install SoapyAirSpy
    become: yes
    command: make install
    args:
      chdir: /home/pi/hamradio/SoapyAirSpy/build

  - name: Clean SoapyAirSpy
    command: make clean
    args:
      chdir: /home/pi/hamradio/SoapyAirSpy/build
