#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyOsmo
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Creates directory hamradio
    file:
      path: /home/pi/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gr-osmosdr
      - libfftw3-dev
      - libusb-1.0-0-dev

  - name: Download latest SoapyOsmo sources
    git:
      repo: https://github.com/pothosware/SoapyOsmo
      dest: /home/pi/hamradio/SoapyOsmo

  - name: Creates directory SoapyOsmo/build
    file:
      path: /home/pi/hamradio/SoapyOsmo/build
      state: directory

  - name: Build SoapyOsmo CMakeFiles
    command: cmake ..
    args:
      chdir: /home/pi/hamradio/SoapyOsmo/build

  - name: Build SoapyOsmo
    command: make
    args:
      chdir: /home/pi/hamradio/SoapyOsmo/build

  - name: Install SoapyOsmo
    become: yes
    command: make install
    args:
      chdir: /home/pi/hamradio/SoapyOsmo/build

  - name: Clean SoapyOsmo
    command: make clean
    args:
      chdir: /home/pi/hamradio/SoapyOsmo/build
